"""Provider prose, mirrored from where the provider keeps it.

The schema knows every argument and almost nothing about what any of them mean:
811 of the AWS provider's 83,993 attributes carry a description, which is under
one percent. The prose lives in the provider's own repository and is rendered
from there by the registry — so mirroring it means fetching it from there.

**Version-matched, always.** The documentation for the version in the lock file,
never the newest, because an argument that arrived two releases after the one
installed is a suggestion that will not apply.

**Fetched once and kept.** After that it is on disk and works on a plane, which
is the whole point of a mirror rather than a browser tab.

There are two layouts and a reader written against one silently finds nothing
for the other — `website/docs/r/<name>.html.markdown` for the older providers
including AWS, and `docs/resources/<name>.md` for anything generated by
`tfplugindocs`. Both are tried, in that order, and the miss is a silence.
"""

from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

RAW = "https://raw.githubusercontent.com"
TIMEOUT = 6.0

# Where a provider keeps its documentation, in the order to look.
LAYOUTS = (
    "website/docs/{letter}/{name}.html.markdown",
    "docs/{folder}/{name}.md",
)

# `r` and `d` in the legacy layout; the folder name in the modern one.
LEGACY_LETTER = {"resource": "r", "data_source": "d"}
MODERN_FOLDER = {"resource": "resources", "data_source": "data-sources"}

# A source is `namespace/type`, and it goes into a URL. Treated as
# attacker-controlled: it comes out of a lock file in somebody's repository.
SOURCE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}/[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")

FRONT_MATTER = re.compile(r"\A---\n(.*?)\n---\n", re.S)
FENCED = re.compile(r"```(?:terraform|hcl)\n(.*?)```", re.S)
HEADING = re.compile(r"^##\s+(.+)$", re.M)


class NotASource(ValueError):
    """A provider source that will not be put into a URL."""


@dataclass(frozen=True)
class Example:
    """One block of Terraform out of the provider's own documentation."""

    title: str
    body: str


@dataclass(frozen=True)
class Page:
    """One resource's documentation, as it was written."""

    resource: str
    provider: str
    version: str
    summary: str = ""
    text: str = ""
    examples: tuple[Example, ...] = ()
    url: str = ""

    @property
    def has_prose(self) -> bool:
        return bool(self.text.strip())

    def sections(self) -> list[str]:
        return HEADING.findall(self.text)


def repository(source: str) -> str:
    """`hashicorp/aws` is `hashicorp/terraform-provider-aws`."""
    namespace, _, kind = source.partition("/")
    return f"{namespace}/terraform-provider-{kind}"


def short_name(resource: str, source: str) -> str:
    """`aws_s3_bucket` in the `aws` provider is `s3_bucket` in its docs."""
    _namespace, _, kind = source.partition("/")
    prefix = f"{kind}_"
    return resource[len(prefix) :] if resource.startswith(prefix) else resource


def urls_for(resource: str, *, source: str, version: str, kind: str = "resource") -> list[str]:
    """Every place this page might be, newest layout last."""
    if not SOURCE.match(source):
        raise NotASource(source)
    name = short_name(resource, source)
    tag = version if version.startswith("v") else f"v{version}"
    return [
        f"{RAW}/{repository(source)}/{tag}/"
        + layout.format(
            letter=LEGACY_LETTER.get(kind, "r"),
            folder=MODERN_FOLDER.get(kind, "resources"),
            name=name,
        )
        for layout in LAYOUTS
    ]


def parse(text: str, *, resource: str, provider: str, version: str, url: str = "") -> Page:
    """The front matter, the prose and the provider's own examples."""
    summary = ""
    body = text
    found = FRONT_MATTER.match(text)
    if found:
        body = text[found.end() :]
        for line in found.group(1).splitlines():
            if line.startswith("description:"):
                continue
            if line.strip() and not line.startswith(("subcategory", "layout", "page_title")):
                summary = summary or line.strip()
        described = re.search(r"^description:\s*\|-?\n((?:\s{2,}.*\n?)+)", found.group(1), re.M)
        if described:
            summary = " ".join(part.strip() for part in described.group(1).splitlines()).strip()

    return Page(
        resource=resource,
        provider=provider,
        version=version,
        summary=summary,
        text=body.strip(),
        examples=_examples(body),
        url=url,
    )


def _examples(body: str) -> tuple[Example, ...]:
    """Every fenced Terraform block, named by the heading above it."""
    found: list[Example] = []
    headings = [
        (match.start(), match.group(1).strip())
        for match in re.finditer(r"^#{2,3}\s+(.+)$", body, re.M)
    ]
    for block in FENCED.finditer(body):
        title = next(
            (name for at, name in reversed(headings) if at < block.start()),
            "Example",
        )
        said = block.group(1).strip("\n")
        if said.strip():
            found.append(Example(title=title, body=said + "\n"))
    return tuple(found)


def directory(home: Path | None = None) -> Path:
    if home is not None:
        return Path(home) / ".local" / "share" / "backsight" / "docs"
    root = os.environ.get("XDG_DATA_HOME")
    base = Path(root) if root else Path.home() / ".local" / "share"
    return base / "backsight" / "docs"


def _where(resource: str, source: str, version: str, home: Path | None) -> Path:
    safe = re.sub(r"[^A-Za-z0-9_.-]", "-", f"{source}-{version}")
    return directory(home) / safe / f"{resource}.json"


def _fetch(url: str, *, timeout: float = TIMEOUT) -> str:
    request = urllib.request.Request(url, headers={"Accept": "text/plain"})  # noqa: S310
    # https by construction: the scheme is in RAW and every other part is
    # matched against SOURCE, so no caller decides where this goes.
    with urllib.request.urlopen(request, timeout=timeout) as answer:  # noqa: S310
        return answer.read().decode("utf-8")


@dataclass
class Mirror:
    """What has been fetched, and what to do when it has not been."""

    fetch: Callable[[str], str] = _fetch
    home: Path | None = None
    allowed: bool = False
    _kept: dict[str, Page] = field(default_factory=dict)

    def cached(self, resource: str, *, source: str, version: str) -> Page | None:
        """What is already on disk, which is what makes this work offline."""
        found = self._kept.get(f"{source}/{version}/{resource}")
        if found is not None:
            return found
        path = _where(resource, source, version, self.home)
        try:
            stored = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return None
        page = Page(
            resource=resource,
            provider=source,
            version=version,
            summary=str(stored.get("summary", "")),
            text=str(stored.get("text", "")),
            examples=tuple(
                Example(title=str(one.get("title", "")), body=str(one.get("body", "")))
                for one in stored.get("examples") or []
            ),
            url=str(stored.get("url", "")),
        )
        self._kept[f"{source}/{version}/{resource}"] = page
        return page

    def get(
        self, resource: str, *, source: str, version: str, kind: str = "resource"
    ) -> Page | None:
        """The page, from disk if it is there and from the provider if not.

        Returns None rather than raising when it cannot be had. Documentation
        that will not load is a gap, never a failure of the thing somebody was
        actually doing.
        """
        already = self.cached(resource, source=source, version=version)
        if already is not None:
            return already
        if not self.allowed:
            return None
        try:
            for url in urls_for(resource, source=source, version=version, kind=kind):
                try:
                    text = self.fetch(url)
                except urllib.error.HTTPError as refused:
                    if refused.code == 404:
                        continue
                    return None
                page = parse(text, resource=resource, provider=source, version=version, url=url)
                self._keep(page)
                return page
        except (NotASource, urllib.error.URLError, TimeoutError, OSError, ValueError):
            return None
        return None

    def _keep(self, page: Page) -> None:
        self._kept[f"{page.provider}/{page.version}/{page.resource}"] = page
        path = _where(page.resource, page.provider, page.version, self.home)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(
                json.dumps(
                    {
                        "summary": page.summary,
                        "text": page.text,
                        "url": page.url,
                        "examples": [
                            {"title": one.title, "body": one.body} for one in page.examples
                        ],
                    }
                ),
                encoding="utf-8",
            )
        except OSError:
            return

    def mirrored(self) -> list[tuple[str, int]]:
        """What is on disk, by provider and version. FR-SCH-21's inventory."""
        base = directory(self.home)
        if not base.is_dir():
            return []
        return sorted(
            (found.name, len(list(found.glob("*.json"))))
            for found in base.iterdir()
            if found.is_dir()
        )
